### ISSUE TITLE
E1-F1-US2

### ISSUE THREAD

**Issue by EhOMiguel** [mdsreq-fga-unb/2022.2-AeroWiki#28]
## User story
Como membro, quero realizar login no site para ter acesso ao sistema.

## Motivação
A porta de entrada da wiki será a página de login, sem ela o usuário não consegue ter acesso a site.
O objetivo é fazer com que o usuário, se cadastrado, possa entrar na wiki.

## Critérios de aceitação
- O usuário pré-cadastrado na wiki deve ser capaz de fazer login com seu email e sua senha.
- O sistema não deverá aceitar um e-mail inválido.

## Tasks
- [x] Construção da tela de login alinhada com o Figma.
- [x] Implementação dos inputs e do botão "entrar".
- [x] Construção banco de dados com o MongoDB.
- [x] Construção o back-end.
- [x] Integração front-end / back-end.
