### ISSUE TITLE
Implementação E2-F2-US1

### ISSUE THREAD

**Issue by EhOMiguel** [mdsreq-fga-unb/2022.2-AeroWiki#30]
## User Story
Como membro, eu quero ser capaz de vizualizar as áreas do sistema para me integrar em todas as áreas da empresa.

## Critérios de aceitação
- O usuário deverá poder ver e entrar em cada área e subárea do menu lateral.
- O usuário deverá poder ver e entrar na página de edição de dados do menu do usuário.
- O usuário deverá poder sair do site pelo botão sair no menu do usuário.

## Tasks
- [x] Criação da tela inicial alinhada com o Figma.
- [x] Criação da tela de área e subárea alinhada com o Figma.
- [x] Criação da tela de projetos alinhada com o Figma.
- [x] Criação das rotas de navegação entre as telas
