### ISSUE TITLE
Implementação E1-F1-US1.

### ISSUE THREAD

**Issue by ArtAssLou** [mdsreq-fga-unb/2022.2-AeroWiki#36]
## User Story

Como membro, devo poder alterar os dados pessoais do meu cadastro atualizar a minha conta.

## Critérios de aceitação

- O usuário deve ter acesso a página de perfil.
- O usuário não poderá alterar CPF, RG, Matrícula, Cargo, Data de nascimento e Setor.

## Tasks

- [x] Criação de testes unitários.
- [x] Criação da tela de perfil alinhada com o Figma.
- [x] Criação do código back-end para editar os dados no banco de dados de usuários.
- [x] Criação de restrições para dados estáticos. 
- [ ] Integração front-end / back-end.
