### ISSUE TITLE
Implementação E1-F2-US1.

### ISSUE THREAD

**Issue by EhOMiguel** [mdsreq-fga-unb/2022.2-AeroWiki#41]
## User Story
Como diretor, eu devo realizar o cadastro de usuários na plataforma para que eles possam ter acesso ao sistema.

## Critérios de aceitação
- O usuário deve conseguir fazer login após ser cadastrado.
- Para efetuar o cadastro o diretor terá que inserir nome, sobrenome, e-mail, matrícula da UnB, setor de atuação e cargo do do novo membro.
- O sistema não deverá aceitar um e-mail inválido.
- O sistema não deverá aceitar uma matrícula da UnB inválida.
- O usuário deverá completar seu cadastro e alterar a senha provisória no primeiro login.

## Tasks
- [ ] Criação de testes unitários.
- [x] Criação da tela de cadastro.
- [ ] Criação do código back-end para adicionar os dados no banco de dados.
- [ ] Validação de e-mail e matrícula.
- [ ] Criação do tratamento para primeiro login.
- [ ] Integraçãofront-end / back-end.
