### ISSUE TITLE
Implementação E1-F2-US2.

### ISSUE THREAD

**Issue by EhOMiguel** [mdsreq-fga-unb/2022.2-AeroWiki#42]
## User Story
Como diretor, eu devo poder editar o cadastro de usuários da plataforma para atualizar a base de dados.

## Critérios de aceitação
- O diretor deverá poder atualizar o setor e status de um membro.

## Tasks
- [x] Criação do botão para editar membros.
- [x] Atualização do código backend para a atualização do diretor.
- [x] Integração front-end / back-end.
