### ISSUE TITLE
Implementação E1-F2-US2

### ISSUE THREAD

**Issue by EhOMiguel** [mdsreq-fga-unb/2022.2-AeroWiki#43]
## User Story
Como diretor, eu devo poder remover cadastro de usuários da plataforma para removê-los da base de dados do sistema.

## Critérios de aceitação
- O usuário não deverá conseguir fazer login após ser removido do banco.
- O usuário deve ser removido da lista de membros.
- Os dados do usuário devem ser removidos do banco de dados.

## Tasks
- [x] Criação do botão para excluir membros. 
- [x] Criação de código back-end para remover dados no banco.
- [x] Integração front-end / back-end.
