### ISSUE TITLE
Implementação E1-F2-US3

### ISSUE THREAD

**Issue by EhOMiguel** [mdsreq-fga-unb/2022.2-AeroWiki#44]
## User Story
Como diretor, eu devo poder arquivar o cadastro de usuários da plataforma para manter a organização dos usuários.

## Critérios de aceitação
- O usuário não deverá conseguir fazer login após ser arquivado da lista de membros.
- O usuário deve ser removido da lista de membros. 
- Os dados do usuário devem continuar no banco de dados.

## Tasks
- [x] Criação do botão para arquivar usuários.
- [x] Mudança do status no banco de dados.
- [x] Criação de código backend para incapacitar usuários arquivados de fazer login na wiki.
