### ISSUE TITLE
Implementação E2-F1-US2.

### ISSUE THREAD

**Issue by EhOMiguel** [mdsreq-fga-unb/2022.2-AeroWiki#47]
## User Story
Como gerente, eu quero ser capaz de editar papel de membros do sistema para que os papéis de cada usuário estejam em sincronia com seu cargo na Zenit.

## Critérios de aceitação
- Apenas presidente pode editar o papel de um presidente e um diretor.
- Presidente e diretor podem editar os papéis de membros e gerentes

## Tasks
- [x] Código backend para editar os papéis no banco de dados.
- [x] Integração front-end / back-end.
- [x] Códigos para atualizar as restrições de áreas no frontend de acordo com o papel atualizado.
