### ISSUE TITLE
E3 F1 US1

### ISSUE THREAD

**Issue by EhOMiguel** [mdsreq-fga-unb/2022.2-AeroWiki#61]
## User Story
Como gerente, eu quero classificar projetos para saber quais projetos foram finalizados e quais estão em andamento.

## Critérios de aceitação
- Projetos finalizados não podem ser editados

## Tasks
- [x] Criação de campo no banco para salvar o status do projeto
- [x] Criação de codigo front-end onde é possível alterar o status
- [x] Integração front-end / back-end para salvar status no banco de acordo com o status real do projeto
