### ISSUE TITLE
E3 F1 US2

### ISSUE THREAD

**Issue by EhOMiguel** [mdsreq-fga-unb/2022.2-AeroWiki#62]
## User Story
Como gerente, eu quero arquivar projetos que estão inativos.

## Critérios de aceitação
- Projetos arquivados não podem ser acessados
- Projetos arquivados podem ser acessados se reativados
- O conteúdo do projeto deve ser preservado mesmo que arquivado 

## Tasks
- [ ] Criação do botão para arquivar o projeto
- [ ] Criação de requisição para alterar o status no banco
- [ ] Integração front-end / back-end.
- [ ]  Criação de código para incapacitar o acesso ao projeto caso ele esteja arquivado
