### ISSUE TITLE
E3 F1 US3

### ISSUE THREAD

**Issue by EhOMiguel** [mdsreq-fga-unb/2022.2-AeroWiki#63]
## User Story
Como gerente, eu quero excluir projetos que perderam a relevância.

## Critérios de aceitação
- O conteúdo do projeto deve ser totalmente excluído do banco 
- Projetos excluídos não devem ser visíveis na lista de projetos 

## Tasks
- [ ] Criação do botão para excluir projetos. 
- [ ] Criação de código back-end para remover dados no banco.
- [ ] Integração front-end / back-end.
